#!/bin/sh -e

rm -f /pcs/fff7
dd if=/tmp/fff6 of=/pcs/fff7 bs=1M count=1 oflag=direct
echo 3 > /proc/sys/vm/drop_caches
diff /tmp/fff6 /pcs/fff7

dd if=/dev/zero of=/pcs/f bs=1M count=1; sync; ~/bin_test/aio-verify /pcs/f
dd if=/dev/zero of=/pcs/f bs=1M count=1; sync; ~/bin_test/aio-verify1 /pcs/f
dd if=/dev/zero of=/pcs/f bs=1M count=1; sync; ~/bin_test/aio-verify2 /pcs/f
dd if=/dev/zero of=/pcs/f bs=1M count=1; sync; ~/bin_test/aio-verify3 /pcs/f
dd if=/dev/zero of=/pcs/f bs=1M count=1; sync; ~/bin_test/aio-verify4 /pcs/f

