#!/bin/sh

echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf2_start_$1_m.txt
slabtop -s c -o |head -20 >/tmp/perf2_start_$1_s.txt

for ((i=0;i<100;i++))
do
	ploop mount -m /mnt_ploop/$i /space/$i/DiskDescriptor.xml
done

echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf2_am_$1_m.txt
slabtop -s c -o |head -20 >/tmp/perf2_am_$1_s.txt

for ((i=0;i<100;i++))
do
	umount /mnt_ploop/$i
done

sleep 5
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf2_end_$1_m.txt
slabtop -s c -o |head -20 >/tmp/perf2_end_$1_s.txt

for ((i=0;i<100;i++))
do
        ploop umount /space/$i/DiskDescriptor.xml
done

