#!/bin/sh

#echo 3 > /proc/sys/vm/drop_caches
#cat /proc/meminfo > /tmp/perf1_start.txt
for ((i=0;i<1000;i++))
do
	ploop umount /space/$i/DiskDescriptor.xml
done
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf2_u.txt
