#!/bin/sh

sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf3_start_$1.txt
for ((i=1;i<129;i++))
do
	mount -t ext4 /dev/sdb$i /mnt_ploop/$i
#	ploop mount -m /mnt_ploop/$i /space/$i/DiskDescriptor.xml
#	ploop mount /space/$i/DiskDescriptor.xml
done
sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf3_end_$1.txt

for ((i=1;i<129;i++))
do
	umount /mnt_ploop/$i
#        ploop umount /space/$i/DiskDescriptor.xml
done

