#!/bin/sh

echo "rlc00 checking..."
diff $1 $2
#diff /mnt_ploop/tmpfil1 $TESTFILES/rlc0_files/tmpfil1
diff /mnt_ploop/tmpfil3 $TESTFILES/rlc0_files/tmpfil3
diff /mnt_ploop/tmpfil5 $TESTFILES/rlc0_files/tmpfil5
diff /mnt_ploop/tmpfil7 $TESTFILES/rlc0_files/tmpfil7
diff /mnt_ploop/tmpfil9 $TESTFILES/rlc0_files/tmpfil9
echo "rlc00 checking DONE"
