#!/bin/sh

cp $TESTFILES/snap_files/f3* /mnt_ploop

cp $TESTFILES/snap_files/f3ss /mnt_ploop/f3s
cp $TESTFILES/snap_files/f2ss /mnt_ploop/f2s
cp $TESTFILES/snap_files/f1ss /mnt_ploop/f1s
cp $TESTFILES/snap_files/f0ss /mnt_ploop/f0s

cp $TESTFILES/snap_files/f3bb /mnt_ploop/f3b
cp $TESTFILES/snap_files/f2bb /mnt_ploop/f2b
cp $TESTFILES/snap_files/f1bb /mnt_ploop/f1b
cp $TESTFILES/snap_files/f0bb /mnt_ploop/f0b

