#!/bin/sh

export LD_LIBRARY_PATH=/root/pt-61024-patched/lib
export PATH=/root/pt-61024-patched/tools:$PATH

mknod /dev/ploop0 b 182 0

ploop mount -f raw -d /dev/ploop0 -b 2048 /pcs/b /pcs/s

rm -rf /tmp/q; dd if=/dev/ploop0 of=/tmp/q bs=512 count=2
od -A d -x /tmp/q

