#!/bin/sh -e
echo "---------$0---------"
echo "---------$0---------" >/dev/ttyS0

rm -f $SPACE/ploop-d1.image $SPACE/ploop-d2.image $SPACE/ploop-d3.image
p_on_raw_2
write_test
sleep 10

ls -l /mnt_ploop/fil
ploop snapshot -F -d /dev/ploop0 $SPACE/ploop-d1.image
sleep 10; ls -l /mnt_ploop/fil
ploop snapshot -F -d /dev/ploop0 $SPACE/ploop-d2.image
sleep 10; ls -l /mnt_ploop/fil
ploop snapshot -F -d /dev/ploop0 $SPACE/ploop-d3.image
sleep 10; ls -l /mnt_ploop/fil

write_kill
p_off1_2

p_on1_d123_2
e2fsck -f /dev/ploop0
mount -t ext4 /dev/ploop0 /mnt_ploop

prepare-tfil /mnt_ploop/fil $TESTFILES/ploop.imageSAV
diff /mnt_ploop/fil /tmp/tfil
if [ "$?" != "0" ]; then
echo "Failed"
exit 1
fi

p_off_2
exit 0
