#!/bin/sh -e
echo "---------$0---------"
echo "---------$0---------" >/dev/ttyS0

p_on_raw
cp $TESTFILES/rlc0_files/tmpfil3 /mnt_ploop
p_off_raw

ploop-grow -s 2g -f raw $SPACE/ploop.image

p_on1_raw
e2fsck -f /dev/ploop0
mount -t ext4 /dev/ploop0 /mnt_ploop

SIZ=`cat /sys/block/ploop0/size`
if [ $SIZ != 4194304 ]; then
echo "Incorrect bsize after ploop-grow: $SIZ"
exit 1
fi

diff $TESTFILES/rlc0_files/tmpfil3 /mnt_ploop/tmpfil3
resize2fs /dev/ploop0 2g
p_off_raw

p_on1_raw
e2fsck -f /dev/ploop0
mount -t ext4 /dev/ploop0 /mnt_ploop
diff $TESTFILES/rlc0_files/tmpfil3 /mnt_ploop/tmpfil3
p_off_raw
exit 0
