#!/bin/sh -e
echo "---------$0---------"
echo "---------$0---------" >/dev/ttyS0

p_on
cp $TESTFILES/rlc0_files/tmpfil3 /mnt_ploop

write_test
sleep 20

ls -l /mnt_ploop/fil
ploop-grow -s 32g -d /dev/ploop0
sleep 1
ls -l /mnt_ploop/fil
write_kill

p_off1
p_on1_
e2fsck -f /dev/ploop0
mount -t ext4 /dev/ploop0 /mnt_ploop
resize2fs /dev/ploop0 32g
p_off

p_on1_
mount -t ext4 /dev/ploop0 /mnt_ploop

SIZ=`cat /sys/block/ploop0/size`
if [ $SIZ != 67108864 ]; then
echo "Incorrect bsize after ploop-grow: $SIZ"
exit 1
fi

diff $TESTFILES/rlc0_files/tmpfil3 /mnt_ploop/tmpfil3
if [ "$?" != "0" ]; then
echo "Failed"
exit 1
fi

prepare-tfil /mnt_ploop/fil $TESTFILES/ploop.imageSAV
diff /mnt_ploop/fil /tmp/tfil
if [ "$?" != "0" ]; then
echo "Failed"
exit 1
fi

p_off
exit 0
