#!/bin/sh -e

dd if=/dev/urandom of=/tmp/t_ref bs=262144 count=1

I=0
while [ $I -le 1010 ]; do
  dd if=/tmp/t_ref of=/dev/ploop0 bs=262144 count=1 seek=$I 2>/dev/null
  I=$(($I+1))
done
echo $0 done!!!!!!
