#!/bin/sh

i=10g

sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perfleak_start_m.txt
ploop mount -m /mnt_ploop/$i /space/$i/DiskDescriptor.xml

sleep 2
sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perfleak_am_m.txt

umount /mnt_ploop/$i

sleep 2
sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perfleak_pm_m.txt

ploop umount /space/$i/DiskDescriptor.xml

sleep 2
sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perfleak_au_m.txt

rmmod pio_pcs; rmmod pio_nfs; rmmod pio_direct; rmmod pfmt_raw; rmmod pfmt_ploop1; rmmod pio_kaio; rmmod ploop

sleep 2
sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perfleak_end_m.txt

