#!/bin/sh

#sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf2_start_$1.txt
for ((i=0;i<100;i++))
do
	ploop mount -m /mnt_ploop/$i /space/$i/DiskDescriptor.xml
#	ploop mount /space/$i/DiskDescriptor.xml
done
#sync
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf2_end_$1.txt

for ((i=0;i<100;i++))
do
        ploop umount /space/$i/DiskDescriptor.xml
done

