#!/bin/sh

echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf1_start_1.txt
for ((i=0;i<100;i++))
do
	ploop mount /space/$i/DiskDescriptor.xml
done
echo 3 > /proc/sys/vm/drop_caches
cat /proc/meminfo > /tmp/perf1_end_1.txt
