#!/bin/sh -e
echo "---------$0---------"
echo "---------$0---------" >/dev/ttyS0

TOT_PAGES=1310720 # 5Gb / 4096
PAGES=0
N=0

D=$SPACE/rlc_store
rm -rf $D
mkdir $D

while [ $PAGES -lt $TOT_PAGES ]; do
	R=$RANDOM
	N=$(($N+1))
	PAGES=$(($PAGES+$R))
	dd if=/dev/urandom of=$D/$N bs=4096 count=$R
done

echo $N $PAGES
du -ks $D
ls $D

p_on_gpt_32GB
DST=/mnt_ploop

INUM=12
echo $INUM

cp $D/* $DST
p_off
ls -l $SPACE/ploop.image

p_on1_
parted /dev/ploop0 print >/dev/null
sleep 1
mount -t ext4 -o balloon_ino=$INUM /dev/ploop0p1 /mnt_ploop

I=0
while [ $I -le $N ]; do
  I=$(($I+1))
  if [ $(($I%4)) -ne 0 ]; then
    rm -f $D/$I $DST/$I
  fi
done
p_off

p_on1_
parted /dev/ploop0 print >/dev/null
sleep 1
mount -t ext4 -o balloon_ino=$INUM /dev/ploop0p1 /mnt_ploop

AV=`df -P /mnt_ploop |tail -1 |sed 's/\ \ */ /g' |cut -d ' ' -f 4`
AV=$(($AV*2))

#ploop-balloon2 -s $AV -d /dev/ploop0 -m /mnt_ploop
ploop-balloon change -s $AV -d /dev/ploop0 -m /mnt_ploop
rlc_random_check
p_off

p_on1_
parted /dev/ploop0 print >/dev/null
sleep 1
mount -t ext4 -o balloon_ino=$INUM /dev/ploop0p1 /mnt_ploop
rlc_random_check
p_off

