#!/bin/sh

for i in `cut -d ':' -f 1 $1`
do
	A=`grep "^$i:" $1 |cut -d ':' -f 2 |sed 's/^\ *//g' |cut -d ' ' -f 1`
	B=`grep "^$i:" $2 |cut -d ':' -f 2 |sed 's/^\ *//g' |cut -d ' ' -f 1`
	if [ "$(($B-$A))" != "0" ]; then
		echo $i $(($B-$A))
	fi
done

